### ISSUE TITLE
Add installation steps in README.md

### ISSUE THREAD

**Issue by jemo662** [KagemaNjoroge/parcelmanager#2]
# PARCEL DELIVERY MANAGER SYSTEM
Parcel Handler System

## Platforms
- iOS
- Android
- Web
- Desktop

## Installation
```bash 
git clone https://github.com/KagemaNjoroge/parcelmanager.git
cd parcelmanager
flutter pub get
flutter run
```

**Comment by KagemaNjoroge** [comment]
# PARCEL DELIVERY MANAGER SYSTEM
Parcel Handler System

## Platforms
- iOS
- Android
- Web
- Desktop


## Installation
```bash 
git clone https://github.com/KagemaNjoroge/parcelmanager.git
cd parcelmanager
flutter pub get
flutter run
```
